# Generated by Django 5.1.2 on 2024-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "model",
            "0032_rename_failureline_job_guid_repository_failure_lin_job_gui_b67c6d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="searchable_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
